version: "3.8"

services:
  backend:
    build: ./backend
    container_name: ticket_backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ticketdb
      JWT_SECRET: mysecretkey
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:14
    container_name: ticket_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticketdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ticket_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

volumes:
  postgres_data:
